==================================================
CNRD CRASH REPORT
==================================================

Time: 2025-04-05 18:19:40
Python version: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]

Exception details:
Type: AttributeError
Message: 'Daemon' object has no attribute 'add_program'

Traceback:
Traceback (most recent call last):
  File "D:\PROJECTS\CNRD PROTOTYPE\bootstrap.py", line 54, in run_game_with_error_handling
    game.main()
  File "D:\PROJECTS\CNRD PROTOTYPE\game.py", line 641, in main
    starter_daemon.add_program(Program("DATA_SIPHON", LOADED_PROGRAMS))
AttributeError: 'Daemon' object has no attribute 'add_program'

Game State Information:
game_state: main_menu
in_combat: False
